name = "posix-submatching"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PosixSubmatching"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[lean_lib]]
name = "PosixSubmatching"
